config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {registrations: "registrations"}
  namespace :teachers do
    resources :questions
    resources :log_exams, only: [:index, :show, :update, :destroy]
    resources :exams do
      collection do
        get :search
      end
    end
    resources :subjects, only: :show
  end

  namespace :students do
    resources :exams, only: :index
    resources :log_exams, except: [:new, :destroy]
  end

  root "application#index"
end

app/models/exam.rb
class Exam < ApplicationRecord
  has_many :exam_questions, dependent: :destroy
  has_many :questions, through: :exam_questions
  has_many :log_exams
  belongs_to :user

  validates :name, presence: true, uniqueness: {scope: :user},
    length: {maximum: Settings.validations.strings.max_length}
  validates :time_for_exam, presence: true
  validates :questions, presence: true
end

app/controllers/students/exams_controller.rb
module Students
  class ExamsController < ApplicationController
    def index
      redirect_to root_path unless current_user.student?
      @exams = Exam.all
    end
  end
end

app/controllers/students/log_exams_controller.rb
module Students
  class LogExamsController < ApplicationController
    before_action :find_log_exam, only: [:show, :edit, :update]

    def index
      @log_exams = current_user.log_exams.submitted
    end

    def show
      @exam = @log_exam.exam
    end

    def create
      @exam = Exam.find params[:exam_id]
      log_exam = LogExam.create!(status: :requested, teacher_id: @exam.user.id,
        user: current_user, exam: @exam)
      redirect_to students_exams_path
    end

    def edit
      @log_exam = current_user.log_exams.find params[:id]
      redirect_to students_exams_path unless @log_exam.approved?
      @exam = @log_exam.exam
      @log_exam.update_attributes! status: :doing
    end

    def update
      LogExam.transaction do
        @log_exam.update_attributes! log_exam_params
        @log_exam.update_attributes! status: :submitted
      end
      redirect_to students_log_exam_path @log_exam
    end

    private
    def log_exam_params
      params.require(:log_exam).permit(log_questions_attributes:
        [:question_id, log_answers_attributes: [:answer_id]])
    end

    def find_log_exam
      @log_exam = LogExam.find params[:id]
    end

    def check_permission
      case params[:action]
      when "index"
        redirect_to root_path if cannot? :read, LogExam
      when "show", "edit", "update"
        redirect_to root_path if @log_exam.user != current_user
      end
    end
  end
end

app/controllers/teachers/exams_controller.rb
module Teachers
  class ExamsController < ApplicationController
    before_action :find_exam, only: [:show, :edit, :update, :destroy]
    before_action :check_permission

    def index
      @exams = Exam.all
    end

    def show ; end

    def new
      @exam = Exam.new
      @questions = Question.all
    end

    def create
      @exam = Exam.new exam_params
      @exam.user = current_user
      if @exam.save
        redirect_to teachers_exams_path
      else
        @questions = Question.all
        render :new
      end
    end

    def edit
      @questions = Question.all
    end

    def update
      if @exam.update_attributes(exam_params)
        redirect_to teachers_exam_path
      else
        @questions = Question.all
        render :edit
      end
    end

    def destroy
      @exam.destroy
      redirect_to teachers_exams_path
    end

    def search
      @exams = Question.find(params[:id]).exams
    end

    private
    def exam_params
      params.require(:exam).permit(:name, :time_for_exam, question_ids: [])
    end

    def find_exam
      @exam = Exam.find params[:id]
    end

    def check_permission
      case params[:action]
      when "index", "show"
        redirect_to root_path if cannot? :read, Exam
      when "new", "create"
        redirect_to root_path if cannot? :create, Exam
      when "edit", "update", "destroy"
        redirect_to root_path if @exam.user != current_user
      end
    end
  end
end

app/helpers/students/log_exams_helper.rb
module Students
  module LogExamsHelper
    def approved_log_exam exam
      current_user.log_exams.find_by exam: exam, status: :approved
    end
  end
end

app/views/students/exams/index.html.erb
<% @exams.each do |exam| %>
  <div class="shadow-lg p-4 mb-4 bg-white" style="border-radius: 1em">
    <h3><%= link_to exam.name, teachers_exam_path(exam) %></h3>
    <small><%= pluralize exam.questions.count, "question" %>,
      updated by <%= exam.user.name %>
      at <%= time_ago_in_words exam.updated_at %></small>
      <br>
    <% exam.questions.group_by(&:subject).each do |k, v| %>
      <span class="badge badge-success"><%= k.name %></span>
    <% end %>
    <br>
    <% if approved_log_exam(exam).nil? %>
      <%= link_to "Send request to teacher", students_log_exams_path(exam_id: exam.id), method: :post %>
    <% else %>
      <%= link_to "Start now", edit_students_log_exam_path(approved_log_exam exam) %>
    <% end %>
  </div>
<% end %>

app/views/students/exams/new.html.erb
<%= hidden_field_tag :remaining_time, @exam.time_for_exam * 60 %>
<div class="timer m-auto">
  <h4 class="text-center">Remaining Time</h4>
  <div id="clock"></div>
</div>
<br>
<br>
<%= form_for @log_exam, url: students_exams_path, method: :post do |exam_form| %>
  <%= exam_form.hidden_field :log_exam_id, value: @log_exam.id %>
  <% @exam.questions.each_with_index do |question, index| %>
    <%= exam_form.fields_for :log_questions, @log_question do |question_form| %>
      <div class="shadow-lg p-4 mb-4 bg-white" style="border-radius: 1em">
        <span><b>Question <%= index + 1 %>: </b></span>
        <%= question_form.hidden_field :subject_name, value: question.subject.name %>
        <%= question_form.hidden_field :content, value: question.content %>
        <span class="text-justify"><%= question.content %></span>
        <div class="ml-4">
          <%= link_to "File attachment", question.file_url %>
          <br>
          <div class="card border-0">
            <div>
              <div class="card-body p-0">
                <ul class="list-group list-group-flush">
                  <% question.answers.each_with_index do |answer, index| %>
                    <%= question_form.fields_for :log_answers, @log_answer do |answer_form| %>
                      <%= answer_form.hidden_field :option, value: answer.option %>
                      <li class="list-group-item">
                        <div class="custom-control custom-checkbox">
                          <%= answer_form.check_box :is_true, {class: "custom-control-input"}, true, false %>
                          <%= answer_form.label :is_true, answer.option, class: "custom-control-label text-dark" %>
                        </div>
                      </li>
                    <% end %>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <%= exam_form.button "Submit", class: "btn btn-primary submit-time-out mb-4" %>
<% end %>